<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="org.testnggroup.Rerun" tests="14" time="0.123" ignored="0" failures="1" timestamp="07 Jan 2023 18:24:28 GMT" skipped="13" hostname="Ajith" errors="0">
  <testcase name="aj" time="0.005" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.005" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.007" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.005" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.000" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.000" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.012" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.005" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.005" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.031" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.008" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.000" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.033" classname="org.testnggroup.Rerun">
    <skipped/>
  </testcase> <!-- aj -->
  <testcase name="aj" time="0.007" classname="org.testnggroup.Rerun">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at org.testnggroup.Rerun.aj(Rerun.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- aj -->
</testsuite> <!-- org.testnggroup.Rerun -->
